name: Notify

on:
  issues:
    types:
      opened
  pull_request_target:
    types:
      - closed

jobs:
  notify-issue:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    environment:
        name: vars
    timeout-minutes: 5
    steps:
      - uses: snow-actions/nostr@v1.7.0
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            Issue by @${{ github.event.sender.login }}: ${{ github.event.issue.title }}
            ${{ github.event.issue.html_url }} #shootingstar
          tags: |
            - ["t", "shootingstar"]
            - ["proxy", "${{ github.event.issue.html_url }}", "web"]
  notify-pr:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    environment:
        name: vars
    timeout-minutes: 5
    steps:
      - uses: snow-actions/nostr@v1.7.0
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            PR merged: ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }} #shootingstar
          tags: |
            - ["t", "shootingstar"]
            - ["proxy", "${{ github.event.pull_request.html_url }}", "web"]
  user-status:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    environment:
        name: vars
    timeout-minutes: 5
    steps:
      - run: echo "expiration=$(date +%s --date '12 hours')" >> $GITHUB_ENV
      - uses: snow-actions/nostr@v1.7.0
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          kind: 30315
          content: |
            #shootingstar ${{ github.event.pull_request.title }}
          tags: |
            - ["d", "general"]
            - ["t", "shootingstar"]
            - ["expiration", "${{ env.expiration }}"]